### ISSUE TITLE
Is GUI version of refquant available?

### ISSUE THREAD

**Issue by Maithy15** [MannLabs/refquant#1]
Hi,

Is the gui version of refquant available? There is an option in commandline but I get the following error when i try it.

Traceback (most recent call last):
  File "C:\Users\m284y\AppData\Local\anaconda3\envs\refquant\Scripts\refquant-script.py", line 33, in <module>
    sys.exit(load_entry_point('refquant', 'console_scripts', 'refquant')())
  File "C:\Users\m284y\AppData\Local\anaconda3\envs\refquant\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\m284y\AppData\Local\anaconda3\envs\refquant\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\m284y\AppData\Local\anaconda3\envs\refquant\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\m284y\AppData\Local\anaconda3\envs\refquant\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\m284y\AppData\Local\anaconda3\envs\refquant\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "d:\software\refquant\refquant\refquant\cli.py", line 31, in gui
    refquant.gui.run()
  File "d:\software\refquant\refquant\refquant\gui.py", line 5, in run
    raise NotImplementedError
NotImplementedError

Thanks
Maithy

**Comment by Maithy15** [comment]
It just realized that it is not implemented yet!
